### ISSUE TITLE
Source map is not written out if source file already contains a sourceMappingURL

### ISSUE THREAD

**Issue by zaygraveyard** [ben-eb/cssnano-cli#1]
When using the `--sourcemap` option and the source file contains a `sourceMappingURL`, the sourcemap is generated but not written out in the minified file.

Example: 
```sh
lessc --source-map style.less style.css
cssnano style.css style.min.css --sourcemap
```

**Comment by ben-eb** [comment]
What do you mean by "not written out"?

**Comment by zaygraveyard** [comment]
I did some more digging and found it only happens if the source file contains a sourceMappingURL

**Comment by ben-eb** [comment]
OK, I did a bit of digging through the test case. Essentially we delegate source map processing to PostCSS, the `--sourcemap` flag is a shortcut for an *inline* map. So when PostCSS finds an external map file it won't write the source map inline.

https://github.com/postcss/postcss/blob/master/docs/source-maps.md

So, you can restore the map comment by passing the `--map` flag. However, cssnano-cli didn't generate a new map file for you, until the last release (`1.0.4`). Now, you can pass an input, output and the map option, like so:

```
cssnano styles.css styles.min.css --map
```

I'm going to drop the `--sourcemap` flag for version 4 so that maps are more consistent with how PostCSS handles them. This won't be for a while, but leaving this here as a reminder.

Sorry it took this long but I've been swamped. 😄

**Comment by zaygraveyard** [comment]
No worries, and thank you for this amazing tool 😄
